### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by svpolonsky** [zkmopro/mopro#252]
# Problem
when using Circom adapter for Android (https://zkmopro.org/docs/adapters/circom/) I get issues with linker

## Details

Undefined symbols for architecture arm64 (main is the name of my .wasm file):
_main_runtime__showSharedRWMemory
_main_runtime__writeBufferMessage

## Acceptance criteria
Ideally, we'd need to get rid of this issue, or suggestions how to modify my circuit to avoid this problem

## Next steps (optional)
Can you reproduce the issue with the attached .zkey and .wasm? I'll send them in your telegram channel - they are way too big.

FYI: I use the following circuit: https://github.com/aptos-labs/aptos-core/tree/main/keyless/circuit

**Comment by svpolonsky** [comment]
Link to files in Telegram: https://t.me/zkmopro/474/820

**Comment by chancehudson** [comment]
Hey @svpolonsky can i get a minimal repro for this issue? It would be acceptable to provide a branch or fork and a script to put the necessary files in place, then a build command.

The error you're encountering it coming from [rust-witness](https://github.com/chancehudson/rust-witness), specifically the c compilation after the wasm->c transpilation.

**Comment by chancehudson** [comment]
@svpolonsky what version of circom was this witness wasm compiled with?

**Comment by vivianjeng** [comment]
I think it is because the rust-witness doesn't handle the runtime
e.g. [`showSharedRWMemory`](https://github.com/arkworks-rs/circom-compat/blob/7f80002b525c0ebc96b18fb1edcd731e4e4dd679/src/witness/witness_calculator.rs#L86)
and it is caused by the [`log()`](https://github.com/aptos-labs/aptos-core/blob/9baf39b6fba7812f09238c91973f61fd0955057c/keyless/circuit/templates/mainTemplate.circom#L99) in circuits 

Typically the `log` should not happen in the production circuits
I would suggest to remove the `log`s

**Comment by chancehudson** [comment]
Ah interesting, rust-witness does properly transpile memory accesses. I'll check to see if it's the `log` causing this and should be able to fix it in rust-witness.

**Comment by svpolonsky** [comment]
Good news, commenting out log() did help me to `cargo run --bin android`
I'd like to run my circuit on Android, next close the issue
